FROM mcr.microsoft.com/powershell:7.0.3-alpine-3.8
COPY ./module/ /tmp/module/
COPY ./actions/dependabot-pr-watcher/pwsh-profile.ps1 /root/.config/powershell/Microsoft.PowerShell_profile.ps1
COPY ./actions/dependabot-pr-watcher /tmp/
ENTRYPOINT ["pwsh","-File","/tmp/RunAction.ps1"]
