FROM endjin/endjin.githubactions.powershell:1
COPY ./module/ /usr/local/share/powershell/Modules/Endjin.PRAutoflow/
COPY ./module/entrypoint.ps1 /tmp/
COPY ./actions/dependabot-pr-parser /tmp/
ENTRYPOINT ["pwsh","-File","/tmp/entrypoint.ps1"]
