FROM mcr.microsoft.com/powershell:7.0.3-alpine-3.8
COPY ./module/ /tmp/module/
COPY ./module/entrypoint.ps1 /tmp/
COPY ./actions/dependabot-pr-parser /tmp/
ENTRYPOINT ["pwsh","-File","/tmp/entrypoint.ps1"]
