name: build
on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      force_publish:
        description: When true, the PowerShell module will be published to PowerShell Gallery irrespective of its version
        required: true
        default: false
        type: boolean

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    outputs:
      semver: ${{ steps.run_build.outputs.SemVer }}
      major: ${{ steps.run_build.outputs.Major }}
      majorMinor: ${{ steps.run_build.outputs.Major }}.${{ steps.run_build.outputs.Minor }}
      preReleaseTag: ${{ steps.run_build.outputs.PreReleaseTag }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: run_build
      name: Run build.ps1
      run: |
        $ErrorActionPreference = "Stop"

        Write-Host "GIT_REF: $env:GIT_REF"
        Write-Host "FORCE_PUBLISH: $env:FORCE_PUBLISH"

        # set whether we are publishing the container image or just validating it
        $doPublish = $env:GIT_REF.StartsWith("refs/tags/") -or $env:FORCE_PUBLISH -eq "true"
        $entrypointTasks = $doPublish ? @("FullBuildAndPublish") : @("FullBuild")

        & ./build.ps1 -Tasks $entrypointTasks
      shell: pwsh
      env:
        GIT_REF: ${{ github.ref }}
        FORCE_PUBLISH: ${{ github.event.inputs.force_publish }}
        BUILDVAR_PowerShellGalleryApiKey: ${{ secrets.ENDJIN_PSGALLERY_APIKEY }}

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "PesterTestResults.xml"
