name: build
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}-1
  cancel-in-progress: true

# permissions:
#   id-token: read
#   contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    outputs:
      semver: ${{ steps.run_build.outputs.SemVer }}
      major: ${{ steps.run_build.outputs.Major }}
      majorMinor: ${{ steps.run_build.outputs.Major }}.${{ steps.run_build.outputs.Minor }}
      preReleaseTag: ${{ steps.run_build.outputs.PreReleaseTag }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: run_build
      name: Run build.ps1
      run: |
        $ErrorActionPreference = "Stop"
        pwsh -f ./build.ps1 -Tasks FullBuild
      shell: pwsh

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        nunit_files: "PesterTestResults.xml"
